/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { AuthRequestDTOCurrencyCode } from './authRequestDTOCurrencyCode';

/**
 * User sign up request
 */
export interface AuthRequestDTO {
  /**
   * User's email address
   * @minLength 1
   */
  email: string;
  /**
   * User's password (min 8 chars max 72 char) at least one uppercase character, at least one lowercase character, at least one digit, without spaces.
   * @minLength 1
   * @pattern ^((?=\S*?[A-Z])(?=\S*?[a-z])(?=\S*?[!@#$%^&*]).{7,})\S$
   */
  password: string;
  /**
   * User's full name
   * @minLength 1
   * @pattern ^[a-zA-zА-Яа-я]* ?[a-zA-zА-Яа-я]*$
   */
  fullName: string;
  /** User's main currency (ISO 4217) */
  currencyCode: AuthRequestDTOCurrencyCode;
}
