/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { AuthRequestDTOCurrencyCode } from './authRequestDTOCurrencyCode';

/**
 * User sign up request
 */
export interface AuthRequestDTO {
  /**
   * User's email address
   * @minLength 1
   */
  email: string;
  /**
   * User's password (min 8 chars).
   * @minLength 1
   */
  password: string;
  /**
   * User's full name
   * @minLength 1
   */
  fullName: string;
  /** User's main currency (ISO 4217) */
  currencyCode: AuthRequestDTOCurrencyCode;
}
