/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * User's main currency (ISO 4217)
 */
export type AuthRequestDTOCurrencyCode = typeof AuthRequestDTOCurrencyCode[keyof typeof AuthRequestDTOCurrencyCode];


export const AuthRequestDTOCurrencyCode = {
  USD: 'USD',
  UAH: 'UAH',
  EUR: 'EUR',
} as const;
