/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * User's main currency code
 */
export type AuthResponseDTOCurrencyCode = typeof AuthResponseDTOCurrencyCode[keyof typeof AuthResponseDTOCurrencyCode];


export const AuthResponseDTOCurrencyCode = {
  USD: 'USD',
  UAH: 'UAH',
  EUR: 'EUR',
} as const;
