/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Status
 */
export type CategoryResponseDTOStatus = typeof CategoryResponseDTOStatus[keyof typeof CategoryResponseDTOStatus];


export const CategoryResponseDTOStatus = {
  ARCHIVED: 'ARCHIVED',
  ACTIVE: 'ACTIVE',
} as const;
