/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Scope
 */
export type CategoryResponseDTOScope = typeof CategoryResponseDTOScope[keyof typeof CategoryResponseDTOScope];


export const CategoryResponseDTOScope = {
  GLOBAL: 'GLOBAL',
  USER: 'USER',
} as const;
