/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { CategoryResponseDTOStatus } from './categoryResponseDTOStatus';
import type { CategoryResponseDTOType } from './categoryResponseDTOType';

/**
 * Get Category
 */
export interface CategoryResponseDTO {
  /** Category ID */
  id?: number;
  /** Name */
  name?: string;
  /** Type */
  type?: CategoryResponseDTOType;
  /** Status */
  status?: CategoryResponseDTOStatus;
  /** Icon */
  icon?: string;
}
