/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { CreateCategoryDTOIcon } from './createCategoryDTOIcon';
import type { CreateCategoryDTOType } from './createCategoryDTOType';

/**
 * Create a new category
 */
export interface CreateCategoryDTO {
  /**
   * Name
   * @minLength 1
   */
  name: string;
  /** Type */
  type: CreateCategoryDTOType;
  /** Icon */
  icon: CreateCategoryDTOIcon;
}
