/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { TransactionCreateRequestDTO } from './transactionCreateRequestDTO';

export type CreateTransactionBody = {
  dto: TransactionCreateRequestDTO;
  /** Allowed formats: jpg, jpeg, png, webp, pdf. Maximum 10 files. */
  receipts?: Blob[];
};
