/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

export type DeleteTransactionRecurringScope = typeof DeleteTransactionRecurringScope[keyof typeof DeleteTransactionRecurringScope];


export const DeleteTransactionRecurringScope = {
  ONLY_THIS: 'ONLY_THIS',
  THIS_AND_FUTURE: 'THIS_AND_FUTURE',
} as const;
