/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { DeleteTransactionRecurringScope } from './deleteTransactionRecurringScope';

export type DeleteTransactionParams = {
/**
 * How to apply deletion when the transaction belongs to a recurring rule.
 */
recurringScope?: DeleteTransactionRecurringScope;
};
