/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { GetCategoriesTypeItem } from './getCategoriesTypeItem';

export type GetCategoriesParams = {
name?: string;
type?: GetCategoriesTypeItem[];
archived?: boolean;
};
