/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { GetTransactionsType } from './getTransactionsType';

export type GetTransactionsParams = {
accountId?: number;
categoryId?: number;
type?: GetTransactionsType;
dateFrom?: string;
dateTo?: string;
};
