/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

export type GetTransactionsType = typeof GetTransactionsType[keyof typeof GetTransactionsType];


export const GetTransactionsType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
