/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { TransactionCursorRequest } from './transactionCursorRequest';

export type GetTransactionsParams = {
/**
 * Pagination and filter parameters
 */
request: TransactionCursorRequest;
};
