/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Login user request
 */
export interface LoginRequestDto {
  /**
   * User's email address
   * @minLength 1
   */
  email: string;
  /**
   * User's password (min 8 chars).
   * @minLength 1
   */
  password: string;
}
