/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { RecurringTransactionCreateRequestDTOIntervalUnit } from './recurringTransactionCreateRequestDTOIntervalUnit';
import type { RecurringTransactionCreateRequestDTOType } from './recurringTransactionCreateRequestDTOType';

/**
 * Create a recurring transaction. Start date can be today or in the future. Recurrence is calculated from the provided start date.
 */
export interface RecurringTransactionCreateRequestDTO {
  /**
   * Transaction amount, min 0.01 max 999_999_999_999.99
   * @minimum 0.01
   * @maximum 999999999999.99
   */
  amount: number;
  /** Transaction type */
  type: RecurringTransactionCreateRequestDTOType;
  /** Category ID */
  categoryId: number;
  /** Recurring start date. Only today or future is allowed. */
  date: string;
  /** Optional recurring transaction description */
  description?: string;
  /** Optional account ID. If omitted, the default account is used. */
  accountId?: number;
  /** Recurring interval */
  intervalUnit: RecurringTransactionCreateRequestDTOIntervalUnit;
}
