/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Recurring interval
 */
export type RecurringTransactionResponseDTOIntervalUnit = typeof RecurringTransactionResponseDTOIntervalUnit[keyof typeof RecurringTransactionResponseDTOIntervalUnit];


export const RecurringTransactionResponseDTOIntervalUnit = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
