/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Transaction type
 */
export type RecurringTransactionResponseDTOType = typeof RecurringTransactionResponseDTOType[keyof typeof RecurringTransactionResponseDTOType];


export const RecurringTransactionResponseDTOType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
