/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { CategoryResponseDTO } from './categoryResponseDTO';
import type { RecurringTransactionResponseDTOIntervalUnit } from './recurringTransactionResponseDTOIntervalUnit';
import type { RecurringTransactionResponseDTOType } from './recurringTransactionResponseDTOType';

/**
 * Recurring transaction
 */
export interface RecurringTransactionResponseDTO {
  /** Recurring transaction ID */
  id?: number;
  /** Account ID */
  accountId?: number;
  /** Transaction amount */
  amount?: number;
  /** Category */
  category?: CategoryResponseDTO;
  /** Optional description */
  description?: string;
  /** Transaction type */
  type?: RecurringTransactionResponseDTOType;
  /** Recurring start date */
  startDate?: string;
  /** Next execution date */
  nextExecutionDate?: string;
  /** Recurring interval */
  intervalUnit?: RecurringTransactionResponseDTOIntervalUnit;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}
