/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Recurring interval
 */
export type RecurringTransactionCreateRequestDTOIntervalUnit = typeof RecurringTransactionCreateRequestDTOIntervalUnit[keyof typeof RecurringTransactionCreateRequestDTOIntervalUnit];


export const RecurringTransactionCreateRequestDTOIntervalUnit = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
