/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Payload for refreshing authentication token
 */
export interface RefreshTokenRequestDto {
  /**
   * Valid refresh token
   * @minLength 1
   */
  refreshToken: string;
}
