/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { RegistrationRequestDtoCurrencyCode } from './registrationRequestDtoCurrencyCode';

/**
 * User sign up request
 */
export interface RegistrationRequestDto {
  /**
   * User's email address
   * @minLength 1
   */
  email: string;
  /**
   * User's password (min 8 chars max 72 char) at least one uppercase character, at least one lowercase character, at least one digit, without spaces.
   * @minLength 1
   * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':\\|,.<>/?~`])\S{8,72}$
   */
  password: string;
  /**
   * User's full name
   * @minLength 1
   * @pattern ^[A-Za-zА-ЯІЄЇҐа-яієїґ'’ʼ]([A-Za-zА-ЯІЄЇҐа-яієїґ'’ʼ\s-]*[A-Za-zА-ЯІЄЇҐа-яієїґ'’ʼ])?$
   */
  fullName: string;
  /** User's main currency (ISO 4217) */
  currencyCode: RegistrationRequestDtoCurrencyCode;
}
