/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { RegistrationResponseDtoCurrencyCode } from './registrationResponseDtoCurrencyCode';

/**
 * User sign up response
 */
export interface RegistrationResponseDto {
  /** User's id */
  id?: number;
  /** User's full name */
  fullName?: string;
  /** User's email */
  email?: string;
  /** User's main currency code */
  currencyCode?: RegistrationResponseDtoCurrencyCode;
  /** User's avatar url */
  avatarUrl?: string;
  /** User's activation status */
  isActivated?: boolean;
  /** User's creation date, time */
  createdAt?: string;
}
