/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { RequestUpdateUserProfileDTOCurrencyCode } from './requestUpdateUserProfileDTOCurrencyCode';

export interface RequestUpdateUserProfileDTO {
  /**
   * User's full name
   * @pattern ^[A-Za-zА-ЯІЄЇҐа-яієїґ'’ʼ]([A-Za-zА-ЯІЄЇҐа-яієїґ'’ʼ\s-]*[A-Za-zА-ЯІЄЇҐа-яієїґ'’ʼ])?$
   */
  fullName?: string;
  /** User's main currency (ISO 4217) */
  currencyCode?: RequestUpdateUserProfileDTOCurrencyCode;
}
