/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * New user's password
 */
export interface ResetPasswordDTO {
  /**
   * User's password (min 8 chars).
   * @minLength 1
   */
  password: string;
  /**
   * User's confirmPassword (min 8 chars).
   * @minLength 1
   */
  confirmPassword: string;
}
