/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { RegistrationRequestDto } from './registrationRequestDto';

export type SignUpBody = {
  dto: RegistrationRequestDto;
  /** Allowed formats: jpg, jpeg, png, gif, webp. */
  avatar?: Blob;
};
