/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Recurring transaction interval unit
 */
export type TransactionResponseDTOIntervalUnit = typeof TransactionResponseDTOIntervalUnit[keyof typeof TransactionResponseDTOIntervalUnit];


export const TransactionResponseDTOIntervalUnit = {
  ONCE: 'ONCE',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
