/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { TransactionCreateRequestDTOType } from './transactionCreateRequestDTOType';

export interface TransactionCreateRequestDTO {
  /** @minimum 0 */
  amount: number;
  type: TransactionCreateRequestDTOType;
  categoryId: number;
  date: string;
  description?: string;
  accountId?: number;
}
