/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { CategoryResponseDTO } from './categoryResponseDTO';
import type { TransactionResponseDTOType } from './transactionResponseDTOType';

export interface TransactionResponseDTO {
  id?: number;
  accountId?: number;
  amount?: number;
  category?: CategoryResponseDTO;
  description?: string;
  type?: TransactionResponseDTOType;
  receiptsUrls?: string[];
  date?: string;
  createdAt?: string;
  updatedAt?: string;
}
