/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Filter by transaction type (INCOME or EXPENSE)
 */
export type TransactionCursorRequestType = typeof TransactionCursorRequestType[keyof typeof TransactionCursorRequestType];


export const TransactionCursorRequestType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
