/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Transaction recurring scope
 */
export type TransactionUpdateRequestDTOTransactionChangeScope = typeof TransactionUpdateRequestDTOTransactionChangeScope[keyof typeof TransactionUpdateRequestDTOTransactionChangeScope];


export const TransactionUpdateRequestDTOTransactionChangeScope = {
  ONLY_THIS: 'ONLY_THIS',
  THIS_AND_FUTURE: 'THIS_AND_FUTURE',
} as const;
