/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { CategoryResponseDTO } from './categoryResponseDTO';
import type { TransactionResponseDTOIntervalUnit } from './transactionResponseDTOIntervalUnit';
import type { TransactionResponseDTOType } from './transactionResponseDTOType';

/**
 * One-time transaction
 */
export interface TransactionResponseDTO {
  /** Transaction ID */
  id?: number;
  /** Account ID */
  accountId?: number;
  /** Recurring transaction interval unit */
  intervalUnit?: TransactionResponseDTOIntervalUnit;
  /** Transaction amount */
  amount?: number;
  /** Category */
  category?: CategoryResponseDTO;
  /** Optional description */
  description?: string;
  /** Transaction type */
  type?: TransactionResponseDTOType;
  /** Receipt URLs */
  receiptsUrls?: string[];
  /** Transaction date */
  date?: string;
  /** Creation timestamp */
  createdAt?: string;
  /** Last update timestamp */
  updatedAt?: string;
}
