/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { TransactionCursorRequestType } from './transactionCursorRequestType';

/**
 * Request parameters for cursor-paginated transactions
 */
export interface TransactionCursorRequest {
  /** Filter by account ID. Only transactions from this account will be returned. */
  accountId?: number;
  /** Filter by category ID. Includes both active and archived categories. */
  categoryId?: number;
  /** Filter by transaction type (INCOME or EXPENSE) */
  type?: TransactionCursorRequestType;
  /** Start date for filtering (inclusive). Format: YYYY-MM-DD */
  dateFrom?: string;
  /** End date for filtering (inclusive). Format: YYYY-MM-DD */
  dateTo?: string;
  /** Opaque cursor for pagination.
- Omit this parameter for the first page
- Use the `nextCursor` value from the previous response for subsequent pages
- Cursors are URL-safe base64 encoded strings
 */
  cursor?: string;
  /**
   * Number of transactions per page. Min 1, Max 100. Default 15.
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  dateRangeValid?: boolean;
}
