/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { TransactionUpdateRequestDTOTransactionChangeScope } from './transactionUpdateRequestDTOTransactionChangeScope';

/**
 * How to apply changes when the transaction belongs to a recurring rule.
 */
export interface TransactionUpdateRequestDTO {
  /**
   * Transaction amount, min 0.01 max 999_999_999_999.99
   * @minimum 0.01
   * @maximum 999999999999.99
   */
  amount: number;
  /** Category ID */
  categoryId: number;
  /** Transaction date. For one-time transactions only past or today is allowed. */
  date: string;
  /** Optional transaction description */
  description?: string;
  /** Optional account ID. If omitted, the default account is used. */
  accountId?: number;
  /** Transaction recurring scope */
  transactionChangeScope?: TransactionUpdateRequestDTOTransactionChangeScope;
}
