/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Interval unit for recurring transaction
 */
export type TransactionCreateRequestDTOIntervalUnit = typeof TransactionCreateRequestDTOIntervalUnit[keyof typeof TransactionCreateRequestDTOIntervalUnit];


export const TransactionCreateRequestDTOIntervalUnit = {
  ONCE: 'ONCE',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
} as const;
