/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

export type TransactionCreateRequestDTOType = typeof TransactionCreateRequestDTOType[keyof typeof TransactionCreateRequestDTOType];


export const TransactionCreateRequestDTOType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
