/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Paginated response with cursor for next page
 */
export interface TransactionCursorPageResponseDTO {
  /** List of transactions on current page */
  data: unknown[];
  /** Cursor for fetching the next page.
- Send this value as `cursor` parameter in the next request
- `null` indicates this is the last page
 */
  nextCursor?: string;
  /** Whether there are more transactions available after this page */
  hasNext: boolean;
  /** Number of transactions returned on this page (equals `limit` except possibly for last page) */
  pageSize: number;
}
