/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Status
 */
export type UpdateCategoryDTOStatus = typeof UpdateCategoryDTOStatus[keyof typeof UpdateCategoryDTOStatus];


export const UpdateCategoryDTOStatus = {
  ARCHIVED: 'ARCHIVED',
  ACTIVE: 'ACTIVE',
} as const;
