/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { UpdateCategoryDTOStatus } from './updateCategoryDTOStatus';
import type { UpdateCategoryDTOType } from './updateCategoryDTOType';

/**
 * Update category
 */
export interface UpdateCategoryDTO {
  /**
   * Name
   * @minLength 1
   */
  name: string;
  /** Type */
  type: UpdateCategoryDTOType;
  /** Icon */
  icon?: string;
  /** Status */
  status: UpdateCategoryDTOStatus;
}
