/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { UpdateTransactionRecurringScope } from './updateTransactionRecurringScope';

export type UpdateTransactionParams = {
/**
 * How to apply changes when the transaction belongs to a recurring rule.
 */
recurringScope?: UpdateTransactionRecurringScope;
};
