/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { UpdateCategoryDTOIcon } from './updateCategoryDTOIcon';

/**
 * Update category
 */
export interface UpdateCategoryDTO {
  /**
   * Name
   * @minLength 1
   */
  name: string;
  /** Icon */
  icon: UpdateCategoryDTOIcon;
}
