/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Type
 */
export type UpdateCategoryDTOType = typeof UpdateCategoryDTOType[keyof typeof UpdateCategoryDTOType];


export const UpdateCategoryDTOType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
