/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Icon
 */
export type UpdateCategoryDTOIcon = typeof UpdateCategoryDTOIcon[keyof typeof UpdateCategoryDTOIcon];


export const UpdateCategoryDTOIcon = {
  TREND_UP: 'TREND_UP',
  AWARD: 'AWARD',
  DOLLAR: 'DOLLAR',
  GIFT: 'GIFT',
  DOCK: 'DOCK',
  BRIEFCASE: 'BRIEFCASE',
  COINS: 'COINS',
  WALLET: 'WALLET',
  PERCENT: 'PERCENT',
  TROPHY: 'TROPHY',
  RECEIPT: 'RECEIPT',
  MONITOR: 'MONITOR',
  GLOBE: 'GLOBE',
  DATABASE: 'DATABASE',
} as const;
