/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Update current user's password request
 */
export interface UpdatePasswordRequestDto {
  /**
   * Current password of the authenticated user.
   * @minLength 1
   */
  currentPassword: string;
  /**
   * New password. Must contain at least one uppercase letter, one lowercase letter, one special character from !@#$%^&*, and must not contain spaces.
   * @minLength 1
   * @pattern ^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':\\|,.<>/?~`]).{8,72}$
   */
  newPassword: string;
  /**
   * Confirmation of the new password. Must match the new password.
   * @minLength 1
   */
  confirmNewPassword: string;
}
