/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */

/**
 * Update user email request
 */
export interface UpdateEmailRequestDto {
  /**
   * New email address
   * @minLength 1
   */
  email: string;
}
