/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * MT Service API
 * REST API Documentation for MT Service
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDTOCurrencyCode } from './userResponseDTOCurrencyCode';

/**
 * Get user info
 */
export interface UserResponseDTO {
  /** User's id */
  id?: number;
  /** User's email address */
  email?: string;
  /** User's full name */
  fullName?: string;
  /** User's main currency (ISO 4217) */
  currencyCode?: UserResponseDTOCurrencyCode;
  /** User's avatar url */
  avatarUrl?: string;
  /** User's activation status */
  isActivated?: boolean;
}
